version: "3.9"

services:
  app:
    build: .
    container_name: fiap-tech-challenge
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck: # Healthcheck da aplicação (usa actuator/health)
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/actuator/health | grep 'UP' || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 20s

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: techchallenge
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  postgres-data:

