version: "3.9"

services:
  fiap-tech-challenge:
    build: .
    container_name: fiap-tech-challenge
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod # Use 'default' para H2, 'prod' para MySQL
    depends_on:
      - mysql

  mysql:
    image: mysql:8.1
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: techchallenge
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
