version: "3.9"

services:
  app:
    build: .
    container_name: fiap-tech-challenge
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod  # Prod usa MySQL
    depends_on:
      - mysql

  mysql:
    image: mysql:8.1
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: techchallenge
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
